[tool.black]
line-length = 100
target-version = ['py311']
skip-string-normalization = false

[tool.flake8]
max-line-length = 100
exclude = .git,__pycache__,docs,build,dist

[tool.bandit]
exclude_dirs = ["tests", "docs"]
skips = ["B101"]  # assert kullanılmasına izin verir, isteğe göre genişletilir

[tool.coverage.run]
branch = true
source = ["app"]